### ISSUE TITLE
Heyyy!!! i would like to explore this app and create a readme file for it can you assign it to me?

### ISSUE THREAD

**Issue by Krishna841** [TusharAMD/Mailtrack#1]

**Comment by TusharAMD** [comment]
Sure

**Comment by Tapabrata-Goswami** [comment]
Does anyone work on the Readme file??

**Comment by TusharAMD** [comment]
@Tapabrata-Goswami Yes I have assigned this issue to @Krishna841

**Comment by Krishna841** [comment]
Heyy!! Can you give a description of what you want in the readme file?

**Comment by TusharAMD** [comment]
In this application we are basically tracking mail using pixel tracking. You can refer this video for more info https://www.youtube.com/watch?v=EbSn3xdAwAQ&ab_channel=TusharAmdoskar
In readme I think we need to put Introduction, How to get started, Contributing rules, Languages used. I think we can refer this repo's readme https://github.com/harshcasper/rotten-scripts

**Comment by JyotiKM29** [comment]
Hey! @TusharAMD . I'm GSSOC'22 contributor . I want to install and test MailTrack Project . Can guide how to do So .

**Comment by TusharAMD** [comment]
@JyotiKM29 There are 2 parts of the project which is frontend and the backend.
The frontend part is created using react and to run it we need to run `npm i` and `npm start` command
This will open the react app
Now to run the backend which is created using flask we need to simply run `python app.py`. The backend contains REST APIs which enable our react to communicate with MongoDB database.
Our current goal is to redesign the whole project and remove the form input for sending email and instead enable user to login from their email id and send emails just like we do in All in one mail apps which are pre-installed on our devices. 
![Screenshot_2022-03-01-16-14-48-197_com android email](https://user-images.githubusercontent.com/59115865/156155094-02696999-6ffa-4ad9-a7ff-77f7b369271b.jpg)

**Comment by Krishna841** [comment]
Hi, actually I had been busy with my exams last week so could not contribute, but the readme's already done, What should I do?

**Comment by TusharAMD** [comment]
@Krishna841 Do you want to add something more to readme then you can or else I will close this issue

**Comment by Krishna841** [comment]
No, the readme looks great.

**Comment by TusharAMD** [comment]
@Krishna841 Ok then I will close the issue
