### ISSUE TITLE
Add Animations on Home Page and Change the favicon and title

### ISSUE THREAD

**Issue by 404-Terror** [TusharAMD/Mailtrack#10]
### Feature description

I want to add some small animations like the svg logo animation, login button hover animation, change some fonts & change the default favicon and title.

I want to work under GSSoC.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by TusharAMD** [comment]
Assigned

**Comment by TusharAMD** [comment]
PR merged 🎉
