### ISSUE TITLE
Make pages responsive

### ISSUE THREAD

**Issue by 404-Terror** [TusharAMD/Mailtrack#12]
### Feature description

Pages aren't mobile responsive. I would like to make them mobile responsive under GSSoC.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by TusharAMD** [comment]
Assigned
