### ISSUE TITLE
No hover effect for buttons and can add a footer with better UI

### ISSUE THREAD

**Issue by prajnaprabhu3** [TusharAMD/Mailtrack#2]

**Comment by Prajnaprabhu3** [comment]
Can I create .css file?

**Comment by TusharAMD** [comment]
Yes sure

**Comment by Prajnaprabhu3** [comment]
hey Tushar, I am almost done with this issue. Anything that should be added in the footer. As in any social media link or something?

**Comment by TusharAMD** [comment]
No as of now you can make PR

**Comment by tasneemahmed123** [comment]
Hi sir  Tushar , I will add a footer  and I will make no hoover for buttons ; I will start working on it tomorrow if you assign me this issue and thanks 🙏

**Comment by TusharAMD** [comment]
Already assigned.

**Comment by TusharAMD** [comment]
@tasneemahmed123 ok since no reply from previous assignee I will assign issue to you

**Comment by tasneemahmed123** [comment]
Thank you sir , I will work on it tomorrow and assign my work to you 🤗

**Comment by tasneemahmed123** [comment]
sir, when   I begin to upload my work on github I don't know well so after my tries on searching how to upload i find it through pull request so iam sorry i created many pull requests but the latest one i create  contain ascreen shot of footer  and files that i add so i am sorry

**Comment by tasneemahmed123** [comment]
@TusharAMD
