### ISSUE TITLE
docs: Add Issue Templates

### ISSUE THREAD

**Issue by maityamit** [TusharAMD/Mailtrack#4]
Changes
Adding Issue templates
Template path ``` .github/ISSUE_TEMPLATE ```

![156198784-b2e8d551-3df4-4aff-a7c7-051a88c344c0](https://user-images.githubusercontent.com/74618071/156572242-320b999a-7e5f-4ad9-93a9-35ae38b6aff3.png)
![156169861-53b91128-a1aa-4751-805e-affb8a4924a3](https://user-images.githubusercontent.com/74618071/156572248-32427143-798b-4b70-9dc6-d331a287a6f4.png)

Contribution towards GSsoc`22, Thank you

**Comment by maityamit** [comment]
I want to work this issue under GSSoC'22. 👋
Please assign me.

**Comment by TusharAMD** [comment]
Assigned @maityamit
