### ISSUE TITLE
Documentation:  greetings and auto assign workflows

### ISSUE THREAD

**Issue by bartick** [TusharAMD/Mailtrack#7]
### Description

I want to add a these few workflows
1. Greetings - Greets Contributors who is contributing for the 1st time
2. Auto Assign issue - Contributors will be able to auto assign issue (limit 2)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by bartick** [comment]
I want to work on this under GSSoC'22

**Comment by TusharAMD** [comment]
Yes go ahead
